package com.syncchat.app

import android.os.Bundle
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.lifecycleScope
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.syncchat.app.auth.AuthState
import com.syncchat.app.auth.AuthViewModel
import com.syncchat.app.auth.FirebaseAuthRepository
import com.syncchat.app.data.api.RetrofitApiRepository
import com.syncchat.app.ui.auth.LoginScreen
import com.syncchat.app.ui.home.HomeScreen
import com.syncchat.app.ui.theme.SyncChatTheme
import kotlinx.coroutines.launch
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue

class MainActivity : ComponentActivity() {

    private val authViewModel: AuthViewModel by lazy {
        ViewModelProvider(
            this,
            object : ViewModelProvider.Factory {
                override fun <T : androidx.lifecycle.ViewModel> create(modelClass: Class<T>): T {
                    @Suppress("UNCHECKED_CAST")
                    return AuthViewModel(
                        authRepository = FirebaseAuthRepository(),
                        apiRepository = RetrofitApiRepository()
                    ) as T
                }
            }
        )[AuthViewModel::class.java]
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            SyncChatTheme {
                val authState by authViewModel.authState.collectAsState()

                when (authState) {
                    is AuthState.LoggedIn -> {
                        HomeScreen(onSignOut = { authViewModel.signOut() })
                    }
                    else -> {
                        LoginScreen(
                            viewModel = authViewModel,
                            onLoginSuccess = { /* Handled by state observation */ },
                            onGoogleSignIn = { launchGoogleSignIn() }
                        )
                    }
                }
            }
        }
    }

    /** Gap 1: Google Sign-In via Credential Manager */
    private fun launchGoogleSignIn() {
        val credentialManager = CredentialManager.create(this)

        // R.string.default_web_client_id is auto-generated by the google-services plugin
        val googleIdOption = GetGoogleIdOption.Builder()
            .setFilterByAuthorizedAccounts(false)
            .setServerClientId(getString(R.string.default_web_client_id))
            .setAutoSelectEnabled(false)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        lifecycleScope.launch {
            try {
                val result = credentialManager.getCredential(this@MainActivity, request)
                val credential = result.credential

                if (credential is CustomCredential &&
                    credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
                ) {
                    val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                    authViewModel.signInWithGoogle(googleIdTokenCredential.idToken)
                }
            } catch (e: GetCredentialException) {
                Log.e("MainActivity", "Google Sign-In failed: ${e.message}")
            }
        }
    }
}